### ISSUE TITLE
JOSS Review : Code analysis tools

### ISSUE THREAD

**Issue by sepandhaghighi** [big-data-lab-team/OrpailleCC#11]
Analyze your code by some proper tools, these tools helps to identify **vulnerability** and **bugs** in source code.

Recommended analyzers :

1. [Codacy](https://www.codacy.com/)
2. [Codefactor](https://www.codefactor.io/)
3. [LGTM](https://lgtm.com/)

also take a look at [Github Marketplace](https://github.com/marketplace?category=code-quality&type=apps).

**Comment by azazel7** [comment]
Fixed using Codacy.
