### ISSUE TITLE
JOSS Review : Community guidelines

### ISSUE THREAD

**Issue by sepandhaghighi** [big-data-lab-team/OrpailleCC#6]
Add these items to your repo :

- `CHANGELOG.md` ([Example](https://keepachangelog.com/en/1.0.0/))
- `AUTHORS.md` ([Example](https://github.com/sepandhaghighi/pycm/blob/master/AUTHORS.md))
- `.github` folder ([Example](https://github.com/sepandhaghighi/pycm/tree/master/.github))
	- `CODE_OF_CONDUCT.md`
	- `CONTRIBUTING.md` (detailed)
	- `ISSUE_TEMPLATE.md`
	- `PULL_REQUEST_TEMPLATE.md`

**Comment by azazel7** [comment]
The missing files have been added.

**Comment by sepandhaghighi** [comment]
@azazel7 Thanks for your efforts!
Please consider the following :
1. Update your email address in `CODE_OF_CONDUCT.md`
2. Update `CONTRIBUTING.md`, test section!!
3. Update `AUTHORS.md` (other authors!!)
4. Add version(1.0) header in `CHANGELOG.md` ([Example](https://github.com/sepandhaghighi/pycm/blob/master/CHANGELOG.md))

**Comment by azazel7** [comment]
The changes have been made.
